id: AFE6A9747
title: Aspiration Written on the Occasion of Princess Sangdé’s Passing in Sikkim
type: translation
pechas:
- I154C1D98
- I95C04687
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:26.721629
  last_modified_at: 2023-01-04 12:06:26.721639
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I154C1D98/4667: D656
  I95C04687/70D6: D656
